use_frameworks!

target 'SwiftEventHandler_Example' do
  pod 'SwiftEventHandler', :path => '../'

  target 'SwiftEventHandler_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
